services:
  - type: web
    name: golden-glow
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: VITE_SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: NODE_ENV
        value: production
